version: latest
image: docker-image
namespace: default
projectId: gcp-project-id

services:
  server:
    replicas: 1
    command: node
    args: ["packages/proxy-server/dist/index.js"]
    serviceAccountName: blobkit-proxy
    resources:
      cpu: 500m
      memory: 512Mi
    paths:
    - /
    healthPath: /api/v1/health
    maxReplicas: 3
    targetCPUUtil: 70
    ingress:
      domain: proxy.blobkit.org
      tlsSecret: blobkit-tls
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.org/mergeable-ingress-type: minion
    environment:
    - name: ESCROW_CONTRACT
      value: "0x2e8e414bc5c6B0b8339853CEDf965B4A28FB4838"  # Mainnet escrow
    - name: ETH_RPC_URL
      valueFrom:
        configMapKeyRef:
          name: blobkit-proxy
          key: eth-rpc-url
    - name: RPC_URL
      valueFrom:
        configMapKeyRef:
          name: blobkit-proxy
          key: eth-rpc-url
    - name: CHAIN_ID
      value: "1"  # Mainnet chain ID

  server-sepolia:
    replicas: 1
    command: node
    args: ["packages/proxy-server/dist/index.js"]
    serviceAccountName: blobkit-proxy-sepolia
    resources:
      cpu: 500m
      memory: 512Mi
    paths:
    - /
    healthPath: /api/v1/health
    maxReplicas: 1
    targetCPUUtil: 70

    ingress:
      domain: proxy-sepolia.blobkit.org
      tlsSecret: blobkit-tls
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.org/mergeable-ingress-type: minion
    environment:
    - name: ESCROW_CONTRACT
      value: "0x1B345402377A44F674376d6e0f6212e3B9991798"  # Sepolia escrow
    - name: ETH_RPC_URL
      valueFrom:
        configMapKeyRef:
          name: blobkit-proxy
          key: sepolia-rpc-url
    - name: RPC_URL
      valueFrom:
        configMapKeyRef:
          name: blobkit-proxy
          key: sepolia-rpc-url
    - name: CHAIN_ID
      value: "11155111"  # Sepolia chain ID


service:
  type: ClusterIP
  port: 80
  protocol: TCP
  targetPort: 8080

verbosity: DEBUG

# Shared environment variables
environment:
- name: PORT
  value: "8080"
- name: HTTP_PROXY_COUNT
  value: "1"
- name: PROXY_FEE_PERCENT
  value: "0"  # 0% fee
- name: MAX_BLOB_SIZE
  value: "131072"  # 128 KiB
- name: JOB_TIMEOUT_SECONDS
  value: "300"  # 5 minutes
- name: GCP_KMS_KEY_NAME
  valueFrom:
    configMapKeyRef:
      name: blobkit-proxy
      key: kms-key-id
- name: REDIS_URL
  valueFrom:
    secretKeyRef:
      name: blobkit-proxy
      key: redis-url
