version: latest
image: docker-image
namespace: default
projectId: gcp-project-id

services:
  server:
    replicas: 1
    command: node
    args: ["packages/proxy-server/dist/index.js"]
    serviceAccountName: blobkit-proxy
    resources:
      cpu: 100m
      memory: 256Mi
    paths:
    - /
    healthPath: /api/v1/health
    maxReplicas: 3
    targetCPUUtil: 70

ingress:
  domain: proxy.blobkit.org
  tlsSecret: ethcf-tls
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/mergeable-ingress-type: minion
  

service:
  type: ClusterIP
  port: 80
  protocol: TCP
  targetPort: 8080

verbosity: DEBUG

# Shared environment variables
environment:
- name: BLOBKIT_KZG_TRUSTED_SETUP_PATH
  value: https://raw.githubusercontent.com/ethereum/c-kzg-4844/refs/heads/main/src/trusted_setup.txt
- name: KZG_TRUSTED_SETUP_PATH
  value: https://raw.githubusercontent.com/ethereum/c-kzg-4844/refs/heads/main/src/trusted_setup.txt
- name: ESCROW_CONTRACT
  value: "0x1B345402377A44F674376d6e0f6212e3B9991798"  # Mainnet escrow
- name: PORT
  value: "8080"
- name: CHAIN_ID
  value: "1"  # Mainnet chain ID
- name: PROXY_FEE_PERCENT
  value: "0"  # 0% fee
- name: MAX_BLOB_SIZE
  value: "131072"  # 128 KiB
- name: JOB_TIMEOUT_SECONDS
  value: "300"  # 5 minutes
- name: GCP_KMS_KEY_NAME
  valueFrom:
    configMapKeyRef:
      name: blobkit-proxy
      key: kms-key-id
- name: RPC_URL
  valueFrom:
    configMapKeyRef:
      name: blobkit-proxy
      key: eth-rpc-url
- name: REQUEST_SIGNING_SECRET
  valueFrom:
    secretKeyRef:
      name: blobkit-proxy
      key: request-signing-secret
- name: REDIS_URL
  valueFrom:
    secretKeyRef:
      name: blobkit-proxy
      key: redis-url
