{{- $chart := include "chart" . }}
{{- $name := include "name" . -}}

{{- range $service, $val := $.Values.services }}
{{- if and .paths (not .disabled) }}
{{- $serviceName := printf "%s-%s" $name $service -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $serviceName }}
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ $serviceName }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/version: {{ $.Values.version | quote }}
    app.kubernetes.io/component: {{ $service }}
    helm.sh/chart: {{ $chart }}
    {{- if .labels}}
{{ toYaml .labels | nindent 4 }}
    {{- end }}
  {{- if $.Values.ingress.annotations }}
  {{- with $.Values.ingress.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  tls:
  - hosts:
      - {{ $.Values.ingress.domain | quote }}
    secretName: {{ $.Values.ingress.tlsSecret }}

  rules:
    - host: {{ $.Values.ingress.domain | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
---
{{- end }}
{{- end }}
