[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
fs_permissions = [
    { access = "read", path = "./" },
    { access = "write", path = "./" }
]

# Compiler settings
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

# Test settings
verbosity = 2
gas_reports = ["*"]
auto_detect_solc = false

# Formatter settings
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"

# Documentation
doc_title = "BlobKit Contracts"
doc_description = "Smart contracts for BlobKit escrow and payment system"

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }

[profile.lite]
fuzz = { runs = 50 }
invariant = { runs = 10 }

# Dependencies
[dependencies]
forge-std = "github.com/foundry-rs/forge-std"
openzeppelin-contracts = "github.com/OpenZeppelin/openzeppelin-contracts@v4.9.3"

# Remappings
remappings = [
    "@forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

